import { execFileSync, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = resolve(projectRoot, "core", "Cargo.toml");
const compiledWasm = resolve(
  projectRoot,
  "core",
  "target",
  "wasm32-unknown-unknown",
  "release",
  "slm_core.wasm",
);
const publicWasm = resolve(projectRoot, "wasm", "slm_core.wasm");
const generatedModule = resolve(projectRoot, "src", "wasm-binary.ts");
const forcePrebuilt = process.argv.includes("--prebuilt");

const cargoProbe = forcePrebuilt
  ? null
  : spawnSync("cargo", ["--version"], { cwd: projectRoot, stdio: "ignore" });
const cargoAvailable = cargoProbe !== null && cargoProbe.status === 0 && !cargoProbe.error;

let wasmSource = publicWasm;
if (cargoAvailable) {
  execFileSync(
    "cargo",
    ["build", "--locked", "--manifest-path", manifest, "--target", "wasm32-unknown-unknown", "--release"],
    { cwd: projectRoot, stdio: "inherit" },
  );
  wasmSource = compiledWasm;
} else {
  if (!existsSync(publicWasm)) {
    const reason = forcePrebuilt ? "prebuilt mode was requested" : "Cargo is unavailable";
    throw new Error(
      `${reason}, but ${publicWasm} is missing. Build and commit the Wasm artifact from a Rust-capable environment.`,
    );
  }
  const reason = forcePrebuilt ? "Prebuilt mode requested" : "Cargo unavailable";
  console.warn(`[wasm] ${reason}; validating the checked-in wasm/slm_core.wasm artifact.`);
}

const bytes = readFileSync(wasmSource);
const module = new WebAssembly.Module(bytes);
const exports = new Set(WebAssembly.Module.exports(module).map((entry) => entry.name));
const requiredExports = [
  "memory",
  "core_abi_version",
  "core_fft_1d",
  "core_fft_2d",
  "core_nudft_sample_targets",
  "core_nudft_synthesize_phase",
  "core_hungarian",
  "core_hungarian_workspace_bytes",
];
for (const name of requiredExports) {
  if (!exports.has(name)) throw new Error(`Compiled Wasm core is missing export: ${name}`);
}
const imports = WebAssembly.Module.imports(module);
if (imports.some((entry) => entry.module !== "env" || !["atan2", "cos", "sin"].includes(entry.name))) {
  throw new Error(`Compiled Wasm core has an unexpected import: ${JSON.stringify(imports)}`);
}
const base64 = bytes.toString("base64");
const sha256 = createHash("sha256").update(bytes).digest("hex");
const chunks = base64.match(/.{1,100}/g) ?? [];
const source = [
  "// Generated by scripts/build-wasm.mjs. Do not edit by hand.",
  "export const SLM_CORE_WASM_BASE64 = [",
  ...chunks.map((chunk) => `  ${JSON.stringify(chunk)},`),
  "].join(\"\");",
  `export const SLM_CORE_WASM_SHA256 = ${JSON.stringify(sha256)};`,
  "",
].join("\n");

mkdirSync(dirname(publicWasm), { recursive: true });
writeFileSync(publicWasm, bytes);
writeFileSync(generatedModule, source);
